import Head from 'next/head';
import Hero from '@/components/Hero';
import Portfolio from '@/components/Portfolio';

export default function Home() {
  return (
    <>
      <Head>
        <title>Beyond 001</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Portfolio />
    </>
  )
}
